org.gradle.jvmargs=-Xmx1G -DsocksProxyHost=127.0.0.1 -DsocksProxyPort=1080
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.java.home=C:/Program Files/Java/zulu25

# Shadowsocks SOCKS5 proxy (127.0.0.1:1080)
systemProp.socksProxyHost=127.0.0.1
systemProp.socksProxyPort=1080

minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

mod_version=1.1.1
maven_group=safeparrots

fabric_api_version=0.153.0+26.1.2
